export const ERROR_CODES = {
  TELEGRAM_USER_NOT_FOUND: 'TELEGRAM_USER_NOT_FOUND',
  PAIR_LINK_NOT_FOUND: 'PAIR_LINK_NOT_FOUND',
  PAIR_LINK_EXPIRED: 'PAIR_LINK_EXPIRED',
  PAIR_LINK_ALREADY_USED: 'PAIR_LINK_ALREADY_USED',
  PAIR_LINK_SELF_ACCEPT_FORBIDDEN: 'PAIR_LINK_SELF_ACCEPT_FORBIDDEN',
  COUPLE_ALREADY_EXISTS: 'COUPLE_ALREADY_EXISTS',
  COUPLE_NOT_FOUND: 'COUPLE_NOT_FOUND',
  CHECK_IN_INVALID_OPTION: 'CHECK_IN_INVALID_OPTION',
  CHECK_IN_TOO_MANY_MOODS: 'CHECK_IN_TOO_MANY_MOODS',
  NOTIFICATION_INVALID_TIME: 'NOTIFICATION_INVALID_TIME',
  TELEGRAM_DELIVERY_FAILED: 'TELEGRAM_DELIVERY_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class DomainError extends Error {
  public constructor(
    public readonly code: ErrorCode,
    message: string,
  ) {
    super(message);
  }
}
